# Generated by Django 4.2.7 on 2023-12-08 09:41

import uuid

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies: list = []

    operations = [
        migrations.CreateModel(
            name="Url",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "public_id",
                    models.UUIDField(
                        db_index=True,
                        default=uuid.uuid4,
                        editable=False,
                        unique=True,
                    ),
                ),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("updated", models.DateTimeField(auto_now=True)),
                ("url", models.URLField(max_length=255, unique=True)),
                (
                    "seo_status",
                    models.CharField(
                        default="DONE", max_length=255, null=True
                    ),
                ),
            ],
            options={
                "db_table": "urls",
            },
        ),
    ]
