# Generated by Django 4.2.7 on 2023-12-08 09:43

import uuid

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("project", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="MailSettings",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "public_id",
                    models.UUIDField(
                        db_index=True,
                        default=uuid.uuid4,
                        editable=False,
                        unique=True,
                    ),
                ),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("updated", models.DateTimeField(auto_now=True)),
                (
                    "mail_folders",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("smtp_server", models.CharField(max_length=255, null=True)),
                ("smtp_port", models.PositiveIntegerField(default=587)),
                ("smtp_username", models.CharField(max_length=255)),
                ("smtp_password", models.CharField(max_length=255)),
                ("imap_ssl", models.BooleanField(default=False)),
                ("imap_server", models.CharField(max_length=255)),
                ("imap_port", models.PositiveIntegerField(default=143)),
                ("imap_username", models.CharField(max_length=255)),
                ("imap_password", models.CharField(max_length=255)),
                (
                    "check_status",
                    models.CharField(
                        default="DONE", max_length=255, null=True
                    ),
                ),
                (
                    "owner",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="mail_settings",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "project",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="mail_settings",
                        to="project.project",
                    ),
                ),
            ],
            options={
                "db_table": "mail_settings",
                "unique_together": {("owner", "project")},
            },
        ),
        migrations.CreateModel(
            name="Mail",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "public_id",
                    models.UUIDField(
                        db_index=True,
                        default=uuid.uuid4,
                        editable=False,
                        unique=True,
                    ),
                ),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("updated", models.DateTimeField(auto_now=True)),
                ("mail_box", models.CharField(max_length=255, null=True)),
                ("mail_id", models.CharField(max_length=512, unique=True)),
                (
                    "replay_to",
                    models.CharField(default=None, max_length=512, null=True),
                ),
                ("author_name", models.CharField(max_length=255)),
                ("author_mail", models.EmailField(max_length=254)),
                ("subject", models.CharField(max_length=512)),
                ("body", models.TextField()),
                ("receive_date", models.DateTimeField()),
                (
                    "mail_settings",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="mail",
                        to="mail.mailsettings",
                    ),
                ),
            ],
            options={
                "db_table": "mails",
                "unique_together": {("mail_settings", "mail_id")},
            },
        ),
    ]
