# Generated by Django 4.2.7 on 2023-12-11 09:42

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("mail", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="mailsettings",
            name="check_date",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
