# Generated by Django 4.2.7 on 2023-12-09 19:00

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("webmaster", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelTable(
            name="payment",
            table="payments",
        ),
    ]
