# Generated by Django 4.2.7 on 2023-12-08 09:44

import uuid

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("webmaster", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="LinkCheck",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "public_id",
                    models.UUIDField(
                        db_index=True,
                        default=uuid.uuid4,
                        editable=False,
                        unique=True,
                    ),
                ),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("updated", models.DateTimeField(auto_now=True)),
                ("url", models.CharField(max_length=255, null=True)),
                ("anchor", models.CharField(max_length=255, null=True)),
                ("published", models.BooleanField(default=False)),
                (
                    "link",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="webmaster.publishpage",
                    ),
                ),
            ],
            options={
                "db_table": "link_checks",
            },
        ),
    ]
